In [194]:
import tensorflow as tf
import pandas as pd
import re
import string
import numpy as np
import torch as nn
import transformers

In [5]:
tf.__version__

'2.1.0'

In [70]:
def replace_regex(targetval,replacedval,regex):
    return re.sub(regex, replacedval, targetval)

In [71]:
def remove_punctuation(s):
    translator = str.maketrans('', '', string.punctuation)
    return s.translate(translator)

In [72]:
train = pd.read_csv('train.csv',encoding='latin-1')

In [73]:
train.head()

ItemID  Sentiment                                      SentimentText
0       1          0                       is so sad for my APL frie...
1       2          0                     I missed the New Moon trail...
2       3          1                            omg its already 7:30 :O
3       4          0            .. Omgaga. Im sooo  im gunna CRy. I'...
4       5          0           i think mi bf is cheating on me!!!   ...

In [74]:
train['SentimentText'] = train['SentimentText'].apply(lambda x: replace_regex(x,'','(http:\/\/(bit\.ly|t\.co|lnkd\.in|tcrn\.ch)\S*)'))
train['SentimentText'] = train['SentimentText'].apply(lambda x: replace_regex(x,'','@\w+'))
train['SentimentText'] = train['SentimentText'].apply(remove_punctuation)
train['SentimentText'] = train['SentimentText'].apply(lambda x: replace_regex(x,' ',' +'))
train['SentimentText'] = train['SentimentText'].str.strip()

In [80]:
train['SentimentText'].loc[90]

'jonas day is almost over'

In [195]:
from transformers import RobertaConfig, TFRobertaForSequenceClassification, RobertaTokenizer, BertTokenizer, RobertaModel

ImportError: cannot import name 'RobertaModel' from 'transformers' (C:\Users\8prab\.conda\envs\conda3.7.2\lib\site-packages\transformers\__init__.py)

In [196]:
configuration = RobertaConfig()
model = RobertaModel.from_pretrained(r'C:\Users\8prab\Google Drive\Work\xooca-git\Roberta-Tensorflow2\roberta.base')

NameError: name 'RobertaModel' is not defined

In [127]:
model.config_class

transformers.configuration_roberta.RobertaConfig

In [128]:
configuration = model.config
configuration

RobertaConfig {
  "architectures": [
    "RobertaForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": null,
  "do_sample": false,
  "eos_token_ids": null,
  "finetuning_task": null,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "id2label": {
    "0": "LABEL_0",
    "1": "LABEL_1"
  },
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "is_decoder": false,
  "label2id": {
    "LABEL_0": 0,
    "LABEL_1": 1
  },
  "layer_norm_eps": 1e-05,
  "length_penalty": 1.0,
  "max_length": 20,
  "max_position_embeddings": 514,
  "model_type": "roberta",
  "num_attention_heads": 12,
  "num_beams": 1,
  "num_hidden_layers": 12,
  "num_labels": 2,
  "num_return_sequences": 1,
  "output_attentions": false,
  "output_hidden_states": false,
  "output_past": true,
  "pad_token_id": null,
  "pruned_heads": {},
  "repetition_penalty": 1.0,
  "temperature": 1.0,
  "top_k": 50,
  "top_p": 1.0,
  "torchscript": false,
  "type_vocab_size": 1,
  "use

In [186]:
tokenizer = RobertaTokenizer.from_pretrained('roberta-base')

ValueError: Calling RobertaTokenizer.from_pretrained() with the path to a single file or url is not supported.Use a model identifier or the path to a directory instead.

In [182]:
tokenizer_bert = BertTokenizer.from_pretrained('bert-base-uncased')

'Ġdog'

In [139]:
tokenizer.convert_tokens_to_ids('ĠHello') 

20920

In [118]:
input_ids = tf.constant(tokenizer.encode("Hello, my dog is cute", add_special_tokens=True))[None, :]
input_ids

<tf.Tensor: shape=(1, 8), dtype=int32, numpy=array([[    0, 20920,     6,   127,  2335,    16, 11962,     2]])>

In [124]:
input_ids = tf.constant(tokenizer.encode("The Hello, my dog austr is cute", add_special_tokens=True))[None, :]
input_ids

<tf.Tensor: shape=(1, 11), dtype=int32, numpy=
array([[    0,    20, 20920,     6,   127,  2335, 28410,   338,    16,
        11962,     2]])>

In [174]:
input_ids = tokenizer.encode_plus("India won the world cup","hello this is india", add_special_tokens=True)
input_ids


{'input_ids': [0, 666, 351, 5, 232, 4946, 2, 2, 20760, 42, 16, 9473, 493, 2],
 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [183]:
input_ids_bert = tokenizer_bert.encode_plus("India won the world cup","hello this is india", add_special_tokens=True,max_length=19, pad_to_max_length=True)
input_ids_bert

{'input_ids': [101,
  2634,
  2180,
  1996,
  2088,
  2452,
  102,
  7592,
  2023,
  2003,
  2634,
  102],
 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1],
 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [185]:
input_ids_bert = tokenizer_bert.encode_plus("India won the world cup","hello this is india", add_special_tokens=True,max_length=100, pad_to_max_length=True)
input_ids_bert

{'input_ids': [101,
  2634,
  2180,
  1996,
  2088,
  2452,
  102,
  7592,
  2023,
  2003,
  2634,
  102,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 'token_type_ids': [0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  1,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,


In [179]:
tokenizer.convert_ids_to_tokens(2) 

'</s>'

In [119]:
tf.expand_dims(input_ids, 0) 

<tf.Tensor: shape=(1, 1, 8), dtype=int32, numpy=array([[[    0, 20920,     6,   127,  2335,    16, 11962,     2]]])>

In [120]:
labels = tf.constant([1])[None, :] 

In [121]:
outputs = model(input_ids)
logits = outputs[0]
logits

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[-0.07220323,  0.03044231]], dtype=float32)>

In [141]:
outputs

(<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[-0.07220323,  0.03044231]], dtype=float32)>,)

In [142]:
import tensorflow as tf
from transformers import RobertaTokenizer, TFRobertaForMaskedLM

tokenizer = RobertaTokenizer.from_pretrained('roberta-base')
model = TFRobertaForMaskedLM.from_pretrained('roberta-base')
input_ids = tf.constant(tokenizer.encode("Hello, my dog is cute", add_special_tokens=True))[None, :]  # Batch size 1
outputs = model(input_ids)
prediction_scores = outputs[0]

In [153]:
import numpy as np
t = np.array(outputs)[0][0][0]

In [154]:
t.shape

(50265,)